import belaDama from "../../assets/cakes/Bela-dama.png";
import cheesecake from "../../assets/cakes/Cheesecake.png";
import cokoMalina from "../../assets/cakes/Coko-malina.png";
import esterhaise from "../../assets/cakes/Esterhaise.png";
import jaffa from "../../assets/cakes/Jaffa.png";
import kinderBueno from "../../assets/cakes/Kinder-Bueno.png";
import moskva from "../../assets/cakes/Moskva.png";
import oreo from "../../assets/cakes/Oreo.png";
import pitaJabuka from "../../assets/cakes/Pita-jabuka.png";
import prase from "../../assets/cakes/Prase.png";
import toffe from "../../assets/cakes/Toffe.png";
import twist from "../../assets/cakes/Twist.png";
import zitoSaSlagom from "../../assets/cakes/Zito-sa-slagom.png";
import dubai from "../../assets/cakes/dubai.png";
import reforma from "../../assets/cakes/reforma.png";
import { ProductType } from "../dataTypes/productTypes";

export const cakes: ProductType[] = [
  {
    id: 1,
    name: "Bela dama",
    description: "Lagani kremasti kolac sa belom cokoladom.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: belaDama,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 2,
    name: "Cheesecake",
    description: "Kremasti cheesecake sa osvezavajucim ukusom.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: cheesecake,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 3,
    name: "Coko malina",
    description: "Spoj cokolade i maline u bogatom kremastom filu.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: cokoMalina,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 4,
    name: "Esterhaise",
    description: "Klasican ukus sa orasima i bogatim filom.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: esterhaise,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 5,
    name: "Jaffa",
    description: "Cokoladni kolac sa prepoznatljivom notom pomorandze.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: jaffa,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 6,
    name: "Kinder Bueno",
    description: "Nezan fil sa lesnikom inspirisan Kinder Bueno ukusom.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: kinderBueno,
    category: "kolac",
    favorite: true,
    new: true,
  },
  {
    id: 7,
    name: "Moskva",
    description: "Vocni i kremasti klasik za ljubitelje laganijih ukusa.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: moskva,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 8,
    name: "Oreo",
    description: "Kremasti Oreo kolac sa hrskavim detaljima.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: oreo,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 9,
    name: "Pita jabuka",
    description: "Domaci ukus jabuke u modernom izdanju.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: pitaJabuka,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 10,
    name: "Prase",
    description: "Bogati kremasti kolac prepoznatljivog izgleda.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: prase,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 11,
    name: "Toffe",
    description: "Karamelasti ukus sa punim i toplim notama.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: toffe,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 12,
    name: "Twist",
    description: "Razigran spoj vise ukusa u jednom kolacu.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: twist,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 13,
    name: "Zito sa slagom",
    description: "Tradicionalni ukus u elegantnom poslasticarskom obliku.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: zitoSaSlagom,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 14,
    name: "Dubai",
    description: "Savremen kolac bogatog i punog ukusa.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: dubai,
    category: "kolac",
    favorite: true,
    new: true,
  },
  {
    id: 15,
    name: "Reforma",
    description: "Poznati orasasti klasik sa bogatim filom.",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: reforma,
    category: "kolac",
    favorite: false,
    new: false,
  },
];

export const favoriteCakes = cakes.filter((cake) => cake.favorite);
