import belaDama from "../../assets/cakes/Bela-dama.png";
import cheesecake from "../../assets/cakes/Cheesecake.png";
import cokoMalina from "../../assets/cakes/Coko-malina.png";
import esterhaise from "../../assets/cakes/Esterhaise.png";
import kinderBueno from "../../assets/cakes/Kinder-Bueno.png";
import moskva from "../../assets/cakes/Moskva.png";
import oreo from "../../assets/cakes/Oreo.png";
import pitaJabuka from "../../assets/cakes/Pita-jabuka.png";
import prase from "../../assets/cakes/Prase.png";
import toffe from "../../assets/cakes/Toffe.png";
import twist from "../../assets/cakes/Twist.png";
import zitoSaSlagom from "../../assets/cakes/Zito-sa-slagom.png";
import dubai from "../../assets/cakes/dubai.png";
import reforma from "../../assets/cakes/reforma.png";
import { ProductType } from "../dataTypes/productTypes";

export const cakes: ProductType[] = [
  {
    id: 1,
    name: "Bela dama",
    description: "Bela čokolada, pistaći, maline",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: belaDama,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 2,
    name: "Cheesecake",
    description: "Plazma, Krem sir, Voće u želeu",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: cheesecake,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 3,
    name: "Coko malina",
    description: "Čokolada, Malina, Puter",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: cokoMalina,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 4,
    name: "Esterhaise",
    description: "Čokolada, Lešnik, Puter",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: esterhaise,
    category: "kolac",
    favorite: false,
    new: false,
  },

  {
    id: 6,
    name: "Kinder Bueno",
    description: "Mlečna čokolada, Lešnik, Mlečna slatka pavlaka",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: kinderBueno,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 7,
    name: "Moskva",
    description: "Višnje, Ananas, Orah",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: moskva,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 8,
    name: "Oreo",
    description: "Keks, Čokolada, Mlečna pavlaka",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: oreo,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 9,
    name: "Pita jabuka",
    description: "Jabuke, Orasi, Cimet, Domaċe testo",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: pitaJabuka,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 10,
    name: "Prase",
    description: "Vanila, Jagoda, Plazma",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: prase,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 11,
    name: "Toffe",
    description: "Mlečna čokolada, Karamela, Krokant keks",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: toffe,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 12,
    name: "Ferrero",
    description: "Crna Čokolada, Mlečna slatka pavlaka, Hrskava čokolada",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: twist,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 13,
    name: "Zito sa slagom",
    description: "Porcija 120g",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: zitoSaSlagom,
    category: "kolac",
    favorite: false,
    new: false,
  },
  {
    id: 14,
    name: "Dubai",
    description: "Pistaći, Kadaif, Mlečna čokolada",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: dubai,
    category: "kolac",
    favorite: true,
    new: false,
  },
  {
    id: 15,
    name: "Reforma",
    description: "Čokolada, Orasi, Puter",
    regularPrice: "",
    salePrice: "",
    onSale: false,
    image: reforma,
    category: "kolac",
    favorite: false,
    new: false,
  },
];

export const favoriteCakes = cakes.filter((cake) => cake.favorite);
